/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c HuaWeiSwitchOS -p /home/repo/dde-session-shell/src/global_util/dbus/huaweiswitchos_interface /home/repo/dde-session-shell/xml/com.huawei.switchos.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef HUAWEISWITCHOS_INTERFACE_H
#define HUAWEISWITCHOS_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DDBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface com.huawei.switchos
 */
class __HuaWeiSwitchOSPrivate;
class __HuaWeiSwitchOS : public DTK_CORE_NAMESPACE::DDBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "com.huawei.switchos"; }

public:
    explicit __HuaWeiSwitchOS(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__HuaWeiSwitchOS();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<uchar> getOsFlag()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getOsFlag"), argumentList);
    }



    inline QDBusPendingReply<uchar> isDualOsSwitchAvail()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("isDualOsSwitchAvail"), argumentList);
    }



    inline QDBusPendingReply<uint> setOsFlag(uchar flag)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(flag);
        return asyncCallWithArgumentList(QStringLiteral("setOsFlag"), argumentList);
    }




Q_SIGNALS: // SIGNALS
    // begin property changed signals

public Q_SLOTS:
    void CallQueued(const QString &callName, const QList<QVariant> &args);

private Q_SLOTS:
    void onPendingCallFinished(QDBusPendingCallWatcher *w);

private:
    __HuaWeiSwitchOSPrivate *d_ptr;
};

namespace com {
  namespace huawei {
    typedef ::__HuaWeiSwitchOS switchos;
  }
}
#endif
