/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c ImageEffect -p /home/repo/dde-session-shell/src/global_util/dbus/imageeffect_interface /home/repo/dde-session-shell/xml/org.deepin.dde.ImageEffect1.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef IMAGEEFFECT_INTERFACE_H
#define IMAGEEFFECT_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DDBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface org.deepin.dde.ImageEffect1
 */
class __ImageEffectPrivate;
class __ImageEffect : public DTK_CORE_NAMESPACE::DDBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "org.deepin.dde.ImageEffect1"; }

public:
    explicit __ImageEffect(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__ImageEffect();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Delete(const QString &effect, const QString &filename)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(effect) << QVariant::fromValue(filename);
        return asyncCallWithArgumentList(QStringLiteral("Delete"), argumentList);
    }

    inline void DeleteQueued(const QString &effect, const QString &filename)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(effect) << QVariant::fromValue(filename);

        CallQueued(QStringLiteral("Delete"), argumentList);
    }


    inline QDBusPendingReply<QString> Get(const QString &effect, const QString &filename)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(effect) << QVariant::fromValue(filename);
        return asyncCallWithArgumentList(QStringLiteral("Get"), argumentList);
    }




Q_SIGNALS: // SIGNALS
    // begin property changed signals

public Q_SLOTS:
    void CallQueued(const QString &callName, const QList<QVariant> &args);

private Q_SLOTS:
    void onPendingCallFinished(QDBusPendingCallWatcher *w);

private:
    __ImageEffectPrivate *d_ptr;
};

namespace org {
  namespace deepin {
    namespace dde {
      typedef ::__ImageEffect ImageEffect1;
    }
  }
}
#endif
